version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  backend:
    build: ./backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app/backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
